#!/usr/bin/python3
"""Initializing all app"""


from flask import Flask, request, render_template
from flask_babel import Babel, _

app = Flask(__name__)
app.config.from_object(Config)

babel = Babel(app)
